[package]
name = "vswhere"
version = "0.1.0"
authors = ["FaultyRAM <explodingpsu@gmail.com>"]
description = "Provides an idiomatic wrapper around invoking the vswhere utility."
repository = "https://github.com/FaultyRAM/vswhere-rs"
readme = "README.md"
keywords = ["vs2017", "detection", "query"]
categories = ["development-tools::build-utils"]
license = "Apache-2.0 OR MIT"

[target.'cfg(target_os = "windows")'.dependencies.serde_json]
version = "1"

[target.'cfg(target_os = "windows")'.dependencies.winapi]
version = "0.3"
features = ["combaseapi", "knownfolders", "shlobj", "winerror"]
